---
- name: Add GPG key for Docker Repository
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
    filename: docker

- name: Install Docker Engine, Docker CLI, Containerd, & Docker Compose
  apt:
    update_cache: true
    name: "{{item}}"
    state: present
    install_recommends: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Set Docker Registry Proxy Configuration
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
              "metrics-addr": "127.0.0.1:9323",
              "experimental": true
      }
